#!/bin/sh

# patch Xcode 8+ to allow plugins to be loaded

xcodePath="/Applications/Xcode.app"
binaryPath="$xcodePath/Contents/MacOS/Xcode"

log_dir="$HOME"/Library/"Application Support"/mySIMBL/logs
createFolder "$log_dir"
exec &>"$log_dir"/installSIMBL.log

if [ $# -eq 0 ]; then
    echo "No arguments supplied"
fi

if [[ "$1" -eq "-un" ]]; then
    # unsign application
    SCRIPTPATH=$(dirname "$0")
    sudo "$SCRIPTPATH"/unsign "$binaryPath"
    status=$?
    if [ $status -eq 0 ]; then
        sudo mv "$binaryPath" "$binaryPath.signed"
        sudo mv "$binaryPath.unsigned" "$binaryPath"
        print "Done!"
    fi
elif [[ "$1" -eq "-ru" ]]; then
    # restore unsigned
    sudo mv "$binaryPath" "$binaryPath.signed"
    sudo mv "$binaryPath.unsigned" "$binaryPath"
    print "Restored unsigned binary"
elif [[ "$1" -eq "-rs" ]]; then
    #restore signed
    sudo mv "$binaryPath" "$binaryPath.unsigned"
    sudo mv "$binaryPath.signed" "$binaryPath"
    print "Restored signed binary"
else
    SCRIPTPATH=$(dirname "$0")
    sudo "$SCRIPTPATH"/unsign "$binaryPath"
    status=$?
    if [ $status -eq 0 ]; then
        sudo mv "$binaryPath" "$binaryPath.signed"
        sudo mv "$binaryPath.unsigned" "$binaryPath"
        print "Done!"
    fi
fi

echo "Done"
