#!/bin/sh

# patch Xcode 8+ to allow plugins to be loaded

xcodePath="/Applications/Xcode.app"
binaryPath="$xcodePath/Contents/MacOS/Xcode"

log_dir="$HOME"/Library/"Application Support"/mySIMBL/logs
createFolder "$log_dir"
exec &>"$log_dir"/installSIMBL.log

# unsign Xcode
if [[ "$1" -eq "-un" ]]; then
    SCRIPTPATH=$(dirname "$0")
    sudo "$SCRIPTPATH"/unsign "$binaryPath"
    status=$?
    if [ $status -eq 0 ]; then
        sudo mv "$binaryPath" "$binaryPath.signed"
        sudo mv "$binaryPath.unsigned" "$binaryPath"
        print "Done!"
    fi
fi

# restore unsigned
if [[ "$1" -eq "-ru" ]]; then
    sudo mv "$binaryPath" "$binaryPath.signed"
    sudo mv "$binaryPath.unsigned" "$binaryPath"
    print "Restored unsigned binary"
fi

#restore signed
if [[ "$1" -eq "-rs" ]]; then
    sudo mv "$binaryPath" "$binaryPath.unsigned"
    sudo mv "$binaryPath.signed" "$binaryPath"
    print "Restored signed binary"
fi

echo "Done"
